project:
  type: website
  output-dir: docs

website:
  favicon: media/fish.png
  title: "Macey Hartmann"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Projects.qmd
        text: Projects
      - href: Presentations.qmd
        text: Presentations
      - href: cv.qmd
        text: CV

format:
  html:
    theme: styles.scss
    light: minty
    dark: superhero
    css: styles.css
    mainfont: "Quicksand"
    toc: true
    page-layout: full
