project:
  type: website
  output-dir: docs

website:
  site-url: https://maceyhartmann.github.io/
  favicon: media/fish.png
  navbar:
    title: "Macey Hartmann"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Projects.qmd
        text: Projects
      - href: SciComm.qmd
        text: Science Communication
      - href: cv.qmd
        text: CV

format:
  html:
    theme: styles.scss
    light: minty
    dark: superhero
    css: styles.css
    mainfont: "Quicksand"
    toc: true
    page-layout: full
