project:
  type: website
  output-dir: docs

website:
  title: "Macey Hartmann"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Projects.qmd
        text: Projects
      - href: Presentations.qmd
        text: Presentations
      - href: cv.qmd
        text: CV

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

